version: "3"

networks:
  agrarserver-main:
    external: true
  agrarserver-intern:
services:
  geoserver:
    build: ./geoserver
    labels:
      - "traefik.frontend.rule=Host:geoserver.${COMPOSE_PROJECT_NAME}.localhost"
      - "traefik.port=8080"
    networks: 
      - agrarserver-main
      - agrarserver-intern
  web:
    build: 
      context: ./web
      args:
      - GEOSERVER_HOST=geoserver.${COMPOSE_PROJECT_NAME}.localhost
      - GATEWAY_HOST=gateway.${COMPOSE_PROJECT_NAME}.localhost
    labels:
      - "traefik.frontend.rule=Host:web.${COMPOSE_PROJECT_NAME}.localhost"
    networks: 
      - agrarserver-main
  postgis:
    image: mdillon/postgis:11-alpine
    networks: 
      - agrarserver-intern
  postgis-seed:
    build: ./postgis-seed
    networks:
      - agrarserver-intern
  gateway:
    build: ./gateway
    labels:
      - "traefik.frontend.rule=Host:gateway.${COMPOSE_PROJECT_NAME}.localhost"
      - "traefik.port=5000"
    environment:
      - GEOSERVER_HOST=geoserver
    networks: 
      - agrarserver-main
  cadvisor:
    image: google/cadvisor:latest
    labels:
      - "traefik.frontend.rule=Host:cadvisor.${COMPOSE_PROJECT_NAME}.localhost"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks: 
      - agrarserver-main

