version: "3"
services:
  geoserver:
    build: ./geoserver
    ports:
      - 8080:8080
  web:
    build: ./web
    ports:
      - 8000:1234
  postgis:
    image: mdillon/postgis:11-alpine
  postgis-seed:
    build: ./postgis-seed
  gateway:
    build: ./gateway
    ports: 
      - 5000:5000
    environment:
      - GEOSERVER_HOST=geoserver
      - GEOSERVER_PORT=8080
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

