version: "3"
services:
  geoserver:
    build: ./geoserver
    ports:
      - 8080:8080
  web:
    build: ./web
    ports:
      - 8000:1234
  postgis:
    image: mdillon/postgis:11-alpine
  postgis-seed:
    build: ./postgis-seed
