swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /bundeslaender:
    get:
      operationId: "bundeslaender.read"
      tags:
        - "Bundeslaender"
      summary: "Bundeslaender of Germany"
      description: "Returns list of german bundeslaender"
      responses:
        200:
          description: "Successful read list of german bundelaender"
  /wfs/insertGeometry:
    post:
      operationId: "wfs.insertGeometry"
      summary: "Inserts a Geometry"
      responses:
        200:
          description: "Successful read list of german bundelaender"
  /wfs/bundeslandContains:
    post:
      operationId: "wfs.bundeslandContains"
      summary: "Inserts a Geometry"
      responses:
        200:
          description: "Successful got containing Bundesland"
  /wfs/overlappingPolygons:
    post:
      operationId: "wfs.overlappingPolygons"
      summary: "Returns overlapping Polygons"
      responses:
        200:
          description: "Successgully retured overlapping polygons"